package ai.devflow.orchestrator;

/** Coarse lifecycle position of a run, surfaced to the UI via SSE. */
public enum RunPhase {
    PREPARING,
    ANALYZING_REQUIREMENTS,
    WAITING_FOR_REQUIREMENTS_CLARIFICATION,
    PLANNING,
    CODING,
    REVIEWING,
    BUILDING,
    COMMITTING,
    OPENING_PR,
    VALIDATING_CI,
    WAITING_FOR_STAGING_APPROVAL,
    VERIFYING_STAGING_PR,
    DISPATCHING_STAGING,
    VERIFYING_STAGING,
    RUNNING_SMOKE_TESTS,
    WAITING_FOR_RELEASE_APPROVAL,
    VERIFYING_RELEASE_PR,
    DISPATCHING_RELEASE,
    VERIFYING_DEPLOYMENT,
    CHECKING_OPERATIONAL_HEALTH,
    WAITING_FOR_ROLLBACK_APPROVAL,
    DISPATCHING_ROLLBACK,
    DONE,
    FAILED
}
